(cl:defpackage face_tracking-srv
  (:use )
  (:export
   "DATAGENERATOR"
   "<DATAGENERATOR-REQUEST>"
   "DATAGENERATOR-REQUEST"
   "<DATAGENERATOR-RESPONSE>"
   "DATAGENERATOR-RESPONSE"
   "DATATRAINER"
   "<DATATRAINER-REQUEST>"
   "DATATRAINER-REQUEST"
   "<DATATRAINER-RESPONSE>"
   "DATATRAINER-RESPONSE"
  ))

